gym_id: Can-Push
log_name: can_push
env_cfg_module: manipulation.tasks.can_push.env_cfg
env_cfg_class: CanPushEnvCfg

episode_length_s: 15.0
success_radius: 0.15

reward_approach_weight:  3.0
reward_push_weight:      5.0
reward_success_weight:   20.0

penalty_drop_weight:          10.0
penalty_right_idle_weight:    0.50
penalty_joint_limits_weight:  0.20
penalty_action_rate_weight:   0.05
penalty_joint_vel_weight:     0.01

can_spawn_x_range: [-0.093, 0.093]
can_spawn_y_range: [-0.082, 0.082]

cameras:
  sideview:
    eye:    [3.5361, -0.3234, 1.1854]
    lookat: [2.5556, -0.3234, 0.9886]
  overview:
    eye:    [1.0010, -3.6746, 1.6016]
    lookat: [1.2826, -2.7235, 1.4747]

viewer:
  resolution: [1280, 720]
  env_index: 0
  origin_type: world