defaults:
  - task: ???
  - algo: ppo
  - sim: default
  - _self_

headless: false
seed: 0
num_envs: 1

num_episodes: 3
deterministic: true
video_fps: 30
video_width: 1280
video_height: 720

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false