defaults:
  - task: ???
  - algo: ppo
  - sim: default
  - _self_

headless: true
seed: 42
num_envs: 4096

log_root: /scratch2/danielc174/humanoid-manipulation/outputs

wandb:
  project: humanoid-manipulation
  mode: disabled

hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false