dt: 0.016667
decimation: 2
render_interval: 2
gravity: [0.0, 0.0, -9.81]

physics_material:
  static_friction: 1.0
  dynamic_friction: 1.0
  restitution: 0.0
  friction_combine_mode: multiply
  restitution_combine_mode: multiply